/**
 * Generated by running the Python that recommendations.ts is a port of:
 * StandardScaler + LinearRegression from server/model_training/regression.py's
 * fit_scaler_and_train_model, over generate_mock_training_data(num_samples=24,
 * random_state=7) from server/model_training/mock_data.py. Regenerate rather
 * than hand-edit if that Python changes.
 *
 * Reproduced with the working interpreter - /usr/bin/python3, not the `python3`
 * first on PATH, which is a local build missing _ctypes and carrying a broken
 * scipy. Verified identical across two runs, so the seeding really is
 * deterministic rather than incidentally stable.
 *
 * The coefficients are the standardised ones: each is the change in
 * average_percentage_viewed per standard deviation of its feature, which is
 * what the 1.0 practical-effect threshold is measured against.
 */
import { AnalysisFeatureRow } from './stats';

export const RECOMMENDATIONS_GOLDEN_ROWS: AnalysisFeatureRow[] = [
  {
    duration: 39.38025066325668,
    wpm: 153.13502173248452,
    scene_change_rate: 7.035045325196605,
    word_count: 6030.4955411485,
    speech_pace_variation: 20.36830135047633,
    speaking_ratio: 0.5563660132014769,
    average_percentage_viewed: 72.72951300727753,
  },
  {
    duration: 54.34675905332665,
    wpm: 146.26138110740092,
    scene_change_rate: 3.209480442606182,
    word_count: 7948.8320378507005,
    speech_pace_variation: 24.02713074329911,
    speaking_ratio: 0.8020020073317644,
    average_percentage_viewed: 56.18848067522573,
  },
  {
    duration: 47.662712963485646,
    wpm: 99.66480578358974,
    scene_change_rate: 4.986380504054098,
    word_count: 4750.295030624782,
    speech_pace_variation: 37.5701497728682,
    speaking_ratio: 0.4967693823950188,
    average_percentage_viewed: 55.24115159775167,
  },
  {
    duration: 17.386395449482553,
    wpm: 139.22614208306726,
    scene_change_rate: 0.9443873175912771,
    word_count: 2420.640763162052,
    speech_pace_variation: 31.894039005707555,
    speaking_ratio: 0.4447006582590102,
    average_percentage_viewed: 59.52803474333851,
  },
  {
    duration: 21.509145670117398,
    wpm: 149.02998109197856,
    scene_change_rate: 3.4072385083304653,
    word_count: 3205.507572522208,
    speech_pace_variation: 21.727865797778023,
    speaking_ratio: 0.7043284683432844,
    average_percentage_viewed: 70.624928664563,
  },
  {
    duration: 53.0454394967944,
    wpm: 152.26617972006616,
    scene_change_rate: 2.92277259693655,
    word_count: 8077.026423748793,
    speech_pace_variation: 21.31424105900041,
    speaking_ratio: 0.6150108588602108,
    average_percentage_viewed: 61.175125741947035,
  },
  {
    duration: 5.2895917511066095,
    wpm: 119.39728468989213,
    scene_change_rate: 1.626497968028389,
    word_count: 631.562892200181,
    speech_pace_variation: 22.49804599482075,
    speaking_ratio: 0.7746079193568334,
    average_percentage_viewed: 68.82752444090787,
  },
  {
    duration: 50.167563011052145,
    wpm: 140.44493447932138,
    scene_change_rate: 6.622535778643067,
    word_count: 7045.780100074445,
    speech_pace_variation: 40.2352940045616,
    speaking_ratio: 1.0,
    average_percentage_viewed: 66.24807132682157,
  },
  {
    duration: 48.838818581362546,
    wpm: 130.4296184388672,
    scene_change_rate: 3.3458462866273435,
    word_count: 6370.028472572175,
    speech_pace_variation: 20.719750574271327,
    speaking_ratio: 0.6252415227881878,
    average_percentage_viewed: 52.21352967915912,
  },
  {
    duration: 30.736422406404643,
    wpm: 133.823255211488,
    scene_change_rate: 7.840609133084162,
    word_count: 4113.2480999803865,
    speech_pace_variation: 21.963196116352705,
    speaking_ratio: 0.6564084620334141,
    average_percentage_viewed: 80.57533890192556,
  },
  {
    duration: 21.666783475062243,
    wpm: 171.21797246772158,
    scene_change_rate: 4.924937697579577,
    word_count: 3709.742736497292,
    speech_pace_variation: 28.525890672852654,
    speaking_ratio: 0.7808105919097048,
    average_percentage_viewed: 70.97537760471663,
  },
  {
    duration: 20.313408665542532,
    wpm: 133.84930649336206,
    scene_change_rate: 5.037921903723885,
    word_count: 2718.9356623991193,
    speech_pace_variation: 23.79229554913545,
    speaking_ratio: 0.8239519937118535,
    average_percentage_viewed: 81.98514976781446,
  },
  {
    duration: 19.017827320976853,
    wpm: 149.3495659010896,
    scene_change_rate: 5.2849743559124915,
    word_count: 2840.3042547697746,
    speech_pace_variation: 23.027157720342775,
    speaking_ratio: 0.7235390901141363,
    average_percentage_viewed: 80.73081731785933,
  },
  {
    duration: 29.47919682354556,
    wpm: 167.6877973476635,
    scene_change_rate: 5.573376828595912,
    word_count: 4943.301582918593,
    speech_pace_variation: 13.859328568489438,
    speaking_ratio: 0.7191104504620175,
    average_percentage_viewed: 68.95902202361381,
  },
  {
    duration: 32.75015424268743,
    wpm: 138.32799134513397,
    scene_change_rate: 1.6309101437627653,
    word_count: 4530.263052634269,
    speech_pace_variation: 24.88478531961452,
    speaking_ratio: 0.8553694432680816,
    average_percentage_viewed: 73.19468277015949,
  },
  {
    duration: 35.442354364097085,
    wpm: 147.76596100831682,
    scene_change_rate: 3.8023510039114066,
    word_count: 5237.173553008118,
    speech_pace_variation: 20.564187770255806,
    speaking_ratio: 0.8279861455550848,
    average_percentage_viewed: 77.98283637879567,
  },
  {
    duration: 59.7525155888916,
    wpm: 152.2092828649896,
    scene_change_rate: 2.296729713721425,
    word_count: 9094.887547164302,
    speech_pace_variation: 36.66127776190223,
    speaking_ratio: 0.5949486251889466,
    average_percentage_viewed: 50.0394294143102,
  },
  {
    duration: 48.596405556756416,
    wpm: 151.27563548510125,
    scene_change_rate: 3.518737235779862,
    word_count: 7351.452132890033,
    speech_pace_variation: 31.53088502701164,
    speaking_ratio: 0.7381228022076237,
    average_percentage_viewed: 58.739619378556505,
  },
  {
    duration: 39.21985761926395,
    wpm: 125.49888347164614,
    scene_change_rate: 1.225280704488092,
    word_count: 4922.048341134559,
    speech_pace_variation: 24.758563869900676,
    speaking_ratio: 0.7552930272992211,
    average_percentage_viewed: 60.81746407050457,
  },
  {
    duration: 59.392808122503666,
    wpm: 151.52280460754017,
    scene_change_rate: 7.758710382866161,
    word_count: 8999.364860239248,
    speech_pace_variation: 31.683810232673437,
    speaking_ratio: 0.5918273066926334,
    average_percentage_viewed: 55.3980689942116,
  },
  {
    duration: 16.841978402957942,
    wpm: 177.17646843483075,
    scene_change_rate: 2.1125302801691,
    word_count: 2984.002254891779,
    speech_pace_variation: 21.601304482868507,
    speaking_ratio: 0.7889758651011545,
    average_percentage_viewed: 80.53111052341802,
  },
  {
    duration: 13.81166186218145,
    wpm: 119.05710643743035,
    scene_change_rate: 5.538238719584637,
    word_count: 1644.3764964035345,
    speech_pace_variation: 35.52126358426947,
    speaking_ratio: 0.6213065284235184,
    average_percentage_viewed: 73.66178957146647,
  },
  {
    duration: 38.68967823501669,
    wpm: 167.18765376043197,
    scene_change_rate: 2.753150611093027,
    word_count: 6468.436528858491,
    speech_pace_variation: 24.946004393283733,
    speaking_ratio: 0.8958100061875565,
    average_percentage_viewed: 65.14917114779092,
  },
  {
    duration: 7.4168104378760855,
    wpm: 152.38708051393164,
    scene_change_rate: 7.055577696121284,
    word_count: 1130.2260893531916,
    speech_pace_variation: 30.833823541804136,
    speaking_ratio: 0.7789118868907609,
    average_percentage_viewed: 82.36192524002671,
  },
];

/** sklearn's model.coef_, in ANALYSIS_FEATURE_COLUMNS order. */
export const RECOMMENDATIONS_GOLDEN_COEFFICIENTS: Record<string, number> = {
  duration: -0.7109700887456089,
  wpm: 1.7163956578320931,
  scene_change_rate: 3.782200976061046,
  word_count: -6.138410739399262,
  speech_pace_variation: -2.060688903251974,
  speaking_ratio: 2.928443471149389,
};

/** sklearn's model.intercept_ - mean(y), since every column is centred. */
export const RECOMMENDATIONS_GOLDEN_INTERCEPT = 67.66159012425676;
